<script lang="ts">import PageHeader from '$lib/components/shell/PageHeader.svelte';</script>
<svelte:head><title>Math Clinic · IMS Academic Hub</title><meta name="description" content="Math Clinic location and verified academic service information." /></svelte:head>
<div class="mx-auto grid w-full max-w-[1180px] gap-8 px-4 py-7 sm:px-6 sm:py-9"><a class="w-fit min-h-11 py-3 font-bold text-muted no-underline" href="/academics">← Academics</a><PageHeader eyebrow="MB 209 · Second floor" title="Math Clinic" description="The service is mapped to MB 209. Schedule-specific help remains unpublished until a verified IMS source is connected." />
<div class="flex flex-wrap gap-2"><a class="inline-flex min-h-12 items-center bg-ims-blue-deep px-4 font-extrabold text-white no-underline" href="/map?room=mb209">View on Map</a><a class="inline-flex min-h-12 items-center border border-line-strong bg-white px-4 font-extrabold no-underline" href="/room/mb209">Room Details</a></div>
<section class="grid divide-y divide-line border-y border-line bg-white md:grid-cols-3 md:divide-x md:divide-y-0">{#each [
 { label:'Location', title:'MB 209', copy:'Second floor · Academic service', rail:'border-ims-blue-deep', href:'/map?room=mb209' },
 { label:'Schedule', title:'No verified schedule loaded.', copy:'The app does not infer tutoring topics, hours, or staff availability.', rail:'border-ims-green', href:null },
 { label:'Data policy', title:'Official information only.', copy:'Source and freshness details appear with every published service record.', rail:'border-ims-yellow', href:null }
] as item}<article class={`grid min-h-52 content-start gap-3 border-t-4 p-5 ${item.rail}`}><span class="font-mono text-xs font-semibold uppercase tracking-[.12em] text-ims-blue-ink">{item.label}</span><h2 class="mt-auto text-2xl font-semibold tracking-tight text-ink-strong">{item.title}</h2><p class="leading-relaxed text-muted">{item.copy}</p>{#if item.href}<a class="min-h-11 py-3 font-bold text-ims-blue-ink" href={item.href}>Navigate in the Building →</a>{/if}</article>{/each}</section></div>
