<script lang="ts">
  import { onMount } from 'svelte'; import { flip } from 'svelte/animate'; import GradeCalculator from './GradeCalculator.svelte'; import AppIcon from '$lib/components/ui/AppIcon.svelte'; import ConfirmDialog from '$lib/components/ui/ConfirmDialog.svelte'; import Skeleton from '$lib/components/ui/Skeleton.svelte'; import { createBlankGradebook, deleteGradebook, isGradebookDocument, listGradebooks, saveGradebook } from '$lib/domain/grades/storage'; import type { GradebookDocument } from '$lib/domain/grades/types';
  let gradebooks=$state<GradebookDocument[]>([]); let selectedId=$state<string|null>(null); let loading=$state(true); let storageError=$state<string|null>(null); let saveTimer:ReturnType<typeof setTimeout>|null=null; let fileInput=$state<HTMLInputElement|null>(null); let deleteConfirmationOpen=$state(false); let reducedMotion=$state(false); const selected=$derived(gradebooks.find((gradebook)=>gradebook.id===selectedId)??null);
  onMount(async()=>{reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;try{gradebooks=await listGradebooks();selectedId=gradebooks[0]?.id??null;}catch(error){storageError=error instanceof Error?error.message:'Could not load local gradebooks.';}finally{loading=false;}});
  async function createGradebook(){const gradebook=createBlankGradebook(`Course ${gradebooks.length+1}`);gradebooks=[gradebook,...gradebooks];selectedId=gradebook.id;await persist(gradebook);}
  async function persist(gradebook:GradebookDocument){try{await saveGradebook(gradebook);storageError=null;}catch(error){storageError=error instanceof Error?error.message:'Could not save gradebook.';}}
  function onGradebookChange(updated:GradebookDocument){gradebooks=gradebooks.map((gradebook)=>gradebook.id===updated.id?updated:gradebook);if(saveTimer)clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(updated),350);}
  async function removeSelected(){if(!selected)return;const id=selected.id;await deleteGradebook(id);gradebooks=gradebooks.filter((gradebook)=>gradebook.id!==id);selectedId=gradebooks[0]?.id??null;deleteConfirmationOpen=false;}
  function exportSelected(){if(!selected)return;const blob=new Blob([JSON.stringify(selected,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${selected.name.trim().replace(/\s+/g,'-').toLowerCase()||'gradebook'}.json`;anchor.click();URL.revokeObjectURL(url);}
  async function importGradebook(event:Event){const input=event.currentTarget as HTMLInputElement;const file=input.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!isGradebookDocument(parsed))throw new Error('This file is not a valid IMS gradebook export.');const imported:GradebookDocument={...parsed,id:crypto.randomUUID(),updatedAt:new Date().toISOString()};gradebooks=[imported,...gradebooks];selectedId=imported.id;await persist(imported);}catch(error){storageError=error instanceof Error?error.message:'Could not import gradebook.';}finally{input.value='';}}
</script>

<div class="grid gap-4 lg:grid-cols-[17rem_minmax(0,1fr)] lg:items-start">
  <aside class="grid content-start gap-4 border border-line-strong bg-white p-4 lg:sticky lg:top-[5.75rem] lg:max-h-[calc(100svh-7rem)] lg:overflow-auto" aria-label="Local gradebooks">
    <div class="flex items-end justify-between gap-3"><div><span class="font-mono text-[.68rem] font-semibold uppercase tracking-[.16em] text-ims-blue-ink">My gradebooks</span><h2 class="mt-1 text-xl font-semibold tracking-tight text-ink-strong">Local courses</h2></div><button class="inline-flex min-h-11 items-center gap-2 rounded-xl bg-ims-blue-deep px-3 font-extrabold text-white hover:bg-ims-blue-ink" type="button" onclick={createGradebook}><AppIcon name="plus" size={17} />New</button></div>
    {#if loading}<Skeleton lines={2} label="Loading gradebooks from this device" />{:else if gradebooks.length===0}<div class="grid gap-2 border-l-4 border-ims-yellow bg-slate-50 p-3"><strong>No local gradebooks yet.</strong><p class="leading-relaxed text-muted">Create one for any course. You do not need an account or official course record.</p><button class="min-h-11 bg-ims-blue-deep px-3 font-bold text-white" type="button" onclick={createGradebook}>Create Gradebook</button></div>{:else}<div class="divide-y divide-line border-y border-line">{#each gradebooks as gradebook (gradebook.id)}<button animate:flip={{duration:reducedMotion?0:180}} type="button" class={`flex min-h-14 w-full items-center justify-between gap-2 border-l-4 px-3 py-2 text-left ${gradebook.id===selectedId?'border-ims-blue-deep bg-sky-50':'border-transparent bg-white hover:bg-slate-50'}`} aria-pressed={gradebook.id===selectedId} onclick={()=>selectedId=gradebook.id}><span class="grid min-w-0 gap-0.5"><strong>{gradebook.name}</strong><small class="text-muted">{gradebook.categories.length} categor{gradebook.categories.length===1?'y':'ies'}</small></span><span aria-hidden="true">→</span></button>{/each}</div>{/if}
    <div class="flex flex-wrap gap-2"><input bind:this={fileInput} class="sr-only" id="gradebook-import" type="file" accept="application/json,.json" onchange={importGradebook}/><label class="inline-flex min-h-11 cursor-pointer items-center border border-line-strong px-3 text-sm font-bold hover:bg-slate-50" for="gradebook-import">Import JSON</label><button class="min-h-11 border border-line-strong px-3 text-sm font-bold hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40" type="button" onclick={exportSelected} disabled={!selected}>Export</button><button class="inline-flex min-h-11 items-center gap-2 border border-red-200 bg-red-50 px-3 text-sm font-bold text-danger hover:bg-red-100 disabled:cursor-not-allowed disabled:opacity-40" type="button" onclick={()=>deleteConfirmationOpen=true} disabled={!selected}><AppIcon name="trash" size={16}/>Delete</button></div>
    <p class="text-xs leading-relaxed text-muted">Gradebooks are stored in IndexedDB on this browser. They are not part of the Supabase academic database.</p>{#if storageError}<p class="border-l-4 border-danger bg-red-50 p-3 text-sm text-red-800" role="alert">{storageError}</p>{/if}
  </aside>
  <section class="min-w-0">{#if selected}{#key selected.id}<GradeCalculator initial={selected} onChange={onGradebookChange}/>{/key}{:else if !loading}<div class="grid gap-3 border-l-4 border-ims-green bg-white p-5"><span class="w-fit border border-green-200 bg-green-50 px-2 py-1 text-xs font-bold text-green-800">Private tool</span><h2 class="text-xl font-semibold">Create a gradebook to start.</h2><p class="leading-relaxed text-muted">Your categories, scores, what-if calculations, and grading scale will stay on this device.</p></div>{/if}</section>
</div>
<ConfirmDialog bind:open={deleteConfirmationOpen} title="Delete this gradebook?" description="This removes the gradebook from this browser. Export it first if you may need the scores later." confirmLabel="Delete Gradebook" onConfirm={removeSelected} onCancel={()=>deleteConfirmationOpen=false}/>
